version: '3.8'

networks:
  web:
    external: true

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5551:80"
    depends_on:
      - server
    networks:
      - web

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - web
