version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5551:80"
    depends_on:
      - server
    networks:
      - web

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5550:3000"
    environment:
      - NODE_ENV=production
    networks:
      - web

networks:
  web:
    external: true
